package simpledb;

import java.util.*;

/**
 * The Join operator implements the relational join operation.
 */
public class Join extends Operator {

    private static final long serialVersionUID = 1L;
    private JoinPredicate mJoinPredicate;
    private DbIterator mChild1;
    private DbIterator mChild2;
    private Tuple mTuple1;

    /**
     * Constructor. Accepts to children to join and the predicate to join them
     * on
     * 
     * @param p
     *            The predicate to use to join the children
     * @param child1
     *            Iterator for the left(outer) relation to join
     * @param child2
     *            Iterator for the right(inner) relation to join
     */
    public Join(JoinPredicate p, DbIterator child1, DbIterator child2) {
        // some code goes here
    	mJoinPredicate = p;
    	mChild1 = child1;
    	mChild2 = child2;
    }

    public JoinPredicate getJoinPredicate() {
        // some code goes here
        return mJoinPredicate;
    }

    /**
     * @return
     *       the field name of join field1. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField1Name() {
        // some code goes here
        return mChild1.getTupleDesc().getFieldName(mJoinPredicate.getField1());
    }

    /**
     * @return
     *       the field name of join field2. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField2Name() {
        // some code goes here
    	return mChild2.getTupleDesc().getFieldName(mJoinPredicate.getField2());
    }

    /**
     * @see simpledb.TupleDesc#merge(TupleDesc, TupleDesc) for possible
     *      implementation logic.
     */
    public TupleDesc getTupleDesc() {
        mChild1.getTupleDesc();
		// some code goes here
    	return TupleDesc.merge(mChild1.getTupleDesc(), mChild2.getTupleDesc());
    }

    public void open() throws DbException, NoSuchElementException,
            TransactionAbortedException {
        // some code goes here
    	super.open();
    	mChild1.open();
    	mChild2.open();
    	if (mChild1.hasNext()) {
    		mTuple1 = mChild1.next();
    	}
    }

    public void close() {
        // some code goes here
    	super.close();
    	mChild1.close();
    	mChild2.close();
    	mTuple1 = null;
    }

    public void rewind() throws DbException, TransactionAbortedException {
        // some code goes here
    	mChild1.rewind();
    	mChild2.rewind();
    	if (mChild1.hasNext()) {
    		mTuple1 = mChild1.next();
    	}
    }

    /**
     * Returns the next tuple generated by the join, or null if there are no
     * more tuples. Logically, this is the next tuple in r1 cross r2 that
     * satisfies the join predicate. There are many possible implementations;
     * the simplest is a nested loops join.
     * <p>
     * Note that the tuples returned from this particular implementation of Join
     * are simply the concatenation of joining tuples from the left and right
     * relation. Therefore, if an equality predicate is used there will be two
     * copies of the join attribute in the results. (Removing such duplicate
     * columns can be done with an additional projection operator if needed.)
     * <p>
     * For example, if one tuple is {1,2,3} and the other tuple is {1,5,6},
     * joined on equality of the first column, then this returns {1,2,3,1,5,6}.
     * 
     * @return The next matching tuple.
     * @see JoinPredicate#filter
     */
    protected Tuple fetchNext() throws TransactionAbortedException, DbException {
        // some code goes here
    	while(mTuple1 != null) {
    		while(mChild2.hasNext() != false) {
    			Tuple t2 = mChild2.next();
    			if (mJoinPredicate.filter(mTuple1, t2) != false) {
    				return merge(mTuple1, t2);
    			}
    		}
    		
    		mChild2.rewind();
    		if (mChild1.hasNext() != false) {
    			mTuple1 = mChild1.next();
    		}
    		else {
    			mTuple1 = null;
    		}
    	}
        return null;
    }
    
    private Tuple merge(Tuple t1, Tuple t2) {
    	Tuple t = new Tuple(getTupleDesc());
    	for (int i = 0; i < mChild1.getTupleDesc().numFields(); i++) {
    		t.setField(i, t1.getField(i));
    	}
    	for (int i = mChild1.getTupleDesc().numFields(); i < getTupleDesc().numFields(); i++) {
    		t.setField(i, t2.getField(i - mChild1.getTupleDesc().numFields()));
    	}
    	return t;
    }

    @Override
    public DbIterator[] getChildren() {
        // some code goes here
    	DbIterator[] result = new DbIterator[2];
    	result[0] = mChild1;
    	result[1] = mChild2;
        return result;
    }

    @Override
    public void setChildren(DbIterator[] children) {
        // some code goes here
    	mChild1 = children[0];
    	mChild2 = children[1];
    }

}
